SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";
SET lc_time_names = 'fr_FR';

DROP DATABASE IF EXISTS metro;

CREATE SCHEMA metro;

USE metro;

DROP TABLE IF EXISTS `LINES`;

CREATE TABLE `LINES` (
    `id` INT(4) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(12) NOT NULL UNIQUE,
    `birthDate` DATE NOT NULL,
    PRIMARY KEY(`id`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `STATIONS`;

CREATE TABLE `STATIONS` (
    `id` INT(8) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(25) NOT NULL UNIQUE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `LINE_HAS_STATION`;

CREATE TABLE `LINE_HAS_STATION` (
    `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `lineID` INT(4) NOT NULL,
    `stationID` INT(8) NOT NULL,
    CONSTRAINT FK_line FOREIGN KEY (`lineID`) REFERENCES `LINES`(`id`)
    ON UPDATE CASCADE
    ON DELETE CASCADE,
    CONSTRAINT FK_stat FOREIGN KEY (`stationID`) REFERENCES `STATIONS`(`id`)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `DRIVERS`;

CREATE TABLE `DRIVERS` (
    `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `lineID` INT(4) NOT NULL,
    `name` VARCHAR(50) NOT NULL UNIQUE,
    `startTime` TIME NOT NULL DEFAULT "06:00:00",
    `endTIme` TIME NOT NULL DEFAULT "15:00:00",
    CONSTRAINT FK_lineID FOREIGN KEY (`lineID`) REFERENCES `LINES`(`id`)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `PASSENGERS`;

CREATE TABLE `PASSENGERS` (
    `id` INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `lineID` INT(4) DEFAULT NULL,
    `name` VARCHAR(50) NOT NULL,
    `email` VARCHAR(50) NOT NULL UNIQUE,
    CONSTRAINT FK_lines FOREIGN KEY (`lineID`) REFERENCES `LINES`(`id`)
    ON UPDATE CASCADE
    ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=UTF8;